repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-install
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.8
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
repos:
- repo: https://github.com/sqlfluff/sqlfluff
  rev: 3.0.7
  hooks:
    - id: sqlfluff-lint
    - id: sqlfluff-fix
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: ./.venv/bin/pytest --cov tests
    language: system
    types: [python]
    pass_filenames: false
    always_run: true
