name: Lint and test

on:
    push:
      branches-ignore:
        - master

jobs:
    dockerfile-linter:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
    python-linter:
        needs: dockerfile-linter
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v4
        - uses: chartboost/ruff-action@v1
    sql-linter:
        needs: dockerfile-linter
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: dsoftwareinc/setup-python-poetry-action@v1
              with:
                python-version: 3.10.0
                poetry-version: 1.8.3
            - run: |
                poetry run sqlfluff lint
    test:
        needs: [dockerfile-linter, python-linter, sql-linter]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - uses: dsoftwareinc/setup-python-poetry-action@v1
              with:
                python-version: 3.10.0
                poetry-version: 1.8.3
            - run: |
                poetry run pytest-vv
